package mocks

import (
	"github.com/stretchr/testify/mock"
	"time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// PostTransaction provides a mock function with given fields: cardNum, amt, txTime
func (_m *Repository) PostTransaction(cardNum string, amt float32, txTime time.Time) (bool, error) {
	ret := _m.Called(cardNum, amt, txTime)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, float32, time.Time) bool); ok {
		r0 = rf(cardNum, amt, txTime)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float32, time.Time) error); ok {
		r1 = rf(cardNum, amt, txTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ViewUnbilledTransactions provides a mock function with given fields: cardNumber
func (_m *Repository) ViewUnbilledTransactions(cardNumber string) []interface{} {
	ret := _m.Called(cardNumber)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(string) []interface{}); ok {
		r0 = rf(cardNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}
